# module code -> [(family, where you meet it in this module)]
MODS = {
"r": [("mismatched","Page numbers are `u64`, lengths are `usize`, and the header's `len` is a `u64`: the offset arithmetic of `PageFile` mixes them."),
      ("no_method","`read_at` and `write_all_at` are methods of `FileExt`, which you have to import."),
      ("move_out_of_borrow","`Stack::pop` takes the head out of `&mut self`; `Option::take` is the answer."),
      ("closure_outlives","The shared-state stage spawns threads: without `move` the closure borrows a local."),
      ("guard_across","`BoundedQueue::push` and `pop` wait on a `Condvar`, which takes your lock guard and gives a new one back.")],
"1a": [("no_method","Positional reads and writes (`read_at`, `write_all_at`) need `use std::os::unix::fs::FileExt;`."),
       ("mismatched","A `PageId` is an `i32` newtype and file offsets are `u64`: converting between them is yours to do on purpose."),
       ("not_mut","All the disk manager's methods take `&self` because many threads share it, so what changes has to be behind a `Mutex` or an atomic."),
       ("not_send","The `DiskIo` trait requires `Send + Sync`: a `RefCell` or `Rc` in your struct makes the whole type fail it."),
       ("moved","A `File` is moved into a struct or a thread; using the old name afterwards is a use of a moved value.")],
"1b": [("closure_outlives","The scheduler's worker thread needs `move` to own its channel and the disk."),
       ("moved","A channel's `Sender` is moved into the thread that uses it; clone it first for a second user."),
       ("not_send","A `Rc`, a `RefCell` or a raw `MutexGuard` inside a request makes it impossible to send to the worker."),
       ("static_needed","A method that starts a thread from `&self` borrows data the thread would keep: share the scheduler with an `Arc`."),
       ("guard_across","The reader-writer latch waits on a `Condvar`: assign the guard that `wait` gives back.")],
"1c": [("read_while_write","Evicting while walking the recency list: collect the victim first, then change the map."),
       ("two_mut","Moving a frame between two lists needs two `&mut`: take it out of one, then put it in the other."),
       ("move_out_of_borrow","Removing a node from a linked structure behind `&mut self` is a job for `take()` or `mem::replace`."),
       ("moved","An id or a value you pushed into a list is gone from its old place: copy the id if you still need it.")],
"1d": [("read_while_write","Updating the history of a frame while looping over the frames."),
       ("two_mut","Two entries of the same map at once (the victim and the newest): look up one, finish, then the other."),
       ("mismatched","Timestamps, `k` and frame ids are different integer types; the k-distance arithmetic needs explicit conversions."),
       ("not_hash","Using a struct as a `HashMap` key needs `Hash` and `Eq`.")],
"1e": [("read_while_write","Four lists and a map of where each page is: moving a page while iterating one of them."),
       ("two_mut","Moving a page from one list to another borrows two lists mutably; take it out first."),
       ("moved","A page id moved into a list is gone from the variable; `PageId` is cheap to copy, so derive `Copy`."),
       ("not_hash","Keys of the ghost lists need `Hash` and `Eq`.")],
"1f": [("two_mut","The buffer pool state (page table, free list, replacer) is one struct; borrowing two of its parts mutably at once needs a different shape or a `Mutex` around the whole."),
       ("read_while_write","Looking a page up in the page table while changing the table in the same expression."),
       ("short_lived","A page guard borrowed from the pool must not outlive the pool."),
       ("missing_lifetime","A guard that holds `&BufferPool` needs a lifetime parameter."),
       ("borrow_moved","Dropping or moving the pool while a guard still borrows it.")],
"1g": [("missing_lifetime","`ReadPageGuard<'a>` and `WritePageGuard<'a>` hold references; the lifetime goes on the struct and on every `impl`."),
       ("short_lived","Returning a guard that borrows a local, or keeping a guard longer than its pool."),
       ("borrow_moved","Moving the pool while a guard exists."),
       ("moved","A guard moved into a closure or a thread is gone from the original place."),
       ("not_send","A `MutexGuard` inside a guard makes the guard not `Send`: you cannot hand it to another thread.")],
"2a": [("mismatched","Slot numbers are `usize` in indexing and `u16` in the page header: casts must be explicit."),
       ("no_method","Reading integers out of bytes is `u32::from_le_bytes`, on a fixed-size array: slices need `try_into`."),
       ("non_exhaustive","A page's kind as an enum: every `match` must cover every kind."),
       ("two_mut","Moving entries inside a page array borrows two slots at once: use `copy_within` or `split_at_mut`."),
       ("immutable_twice","Counters in the page header must be `mut` when you change them.")],
"2b": [("mismatched","The hash is `u32`, the directory index is `usize`, the global depth is `u32`: shifts and masks need explicit conversions."),
       ("type_annot","`collect()` of bucket entries needs to know the collection type."),
       ("read_while_write","Splitting a bucket while iterating its entries."),
       ("two_mut","Two buckets at once during a split or a merge."),
       ("not_hash","A key type needs `Hash` and `Eq` (and here, `Copy` helps).")],
"2c": [("two_mut","A node and its sibling during a borrow or a merge: two mutable pages at once."),
       ("short_lived","A reference into a page that a guard owns, kept after the guard is gone."),
       ("moved","A guard moved down the tree (latch crabbing) is gone from the variable above."),
       ("missing_lifetime","The iterator over leaves holds a guard or a reference: it needs a lifetime or ownership."),
       ("temp_dropped","`tree.lock().unwrap().first()` returns a reference into a temporary guard.")],
"2d": [("two_mut","Tombstone compaction touches the leaf and its neighbour."),
       ("moved","Guards moved into the helper that does the compaction."),
       ("short_lived","A reference into a leaf kept after the leaf's guard is dropped."),
       ("non_exhaustive","A slot is live, a tombstone or free: the `match` must say what to do for each.")],
"3a": [("non_exhaustive","`Value` is an enum of types; every operation `match`es over it and must cover the combinations."),
       ("mismatched","Integers of different widths: `TINYINT` + `INTEGER` is a decision you write."),
       ("no_eq","`==` on `Value` needs `PartialEq`; NULL makes equality three-valued, so you may write your own."),
       ("no_method","Converting between types is `i64::from(x)` or `try_from`, not a method on the value."),
       ("not_hash","Using a `Value` as a hash key needs `Hash`, which floats do not have.")],
"3b": [("mismatched","Offsets inside a tuple are `u16` on the page and `usize` in code."),
       ("no_method","Reading a column out of bytes: `from_le_bytes` on a fixed-size array, via `try_into`."),
       ("moved","A `Tuple` handed to the page is gone from the variable; clone it if you still need it."),
       ("type_annot","Collecting column values needs the collection type.")],
"3c": [("read_while_write","Scanning the heap while inserting into it (the Halloween problem is a runtime cousin of this error)."),
       ("two_mut","The heap and the catalog both change in one operation."),
       ("missing_lifetime","The table iterator borrows the heap: it needs a lifetime."),
       ("short_lived","An iterator that outlives the heap it came from.")],
"3d": [("non_exhaustive","Token and expression kinds are enums; every new kind makes the compiler list the `match`es you forgot."),
       ("moved","A parser that consumes its tokens: using the vector after handing it over."),
       ("type_annot","`parse()` and `collect()` of tokens need annotations."),
       ("read_while_write","Peeking at the next token while advancing the position."),
       ("mismatched","Positions are `usize`, spans are `u32`.")],
"3e": [("missing_lifetime","An executor that borrows its child or the catalog needs a lifetime; `Box<dyn Executor>` often needs to own instead."),
       ("read_while_write","Reading the table while the same executor inserts into it."),
       ("moved","The child executor moved into the parent is gone from the old name."),
       ("two_mut","`self.child.next()` while also changing `self.state`: split the struct or finish one borrow first."),
       ("short_lived","A tuple reference that outlives the page guard it came from.")],
"3f": [("not_hash","Group-by and join keys need `Hash` and `Eq`; floats and `Value` need wrapping."),
       ("read_while_write","Probing the hash table while inserting into it."),
       ("moved","A key moved into the table is gone; clone it first."),
       ("two_mut","Two children of a join mutably at once."),
       ("no_eq","Comparing group keys with `==` needs `PartialEq`.")],
"3g": [("not_hash","Sorting by a key needs `Ord`; `f64` is only `PartialOrd`: use `total_cmp`."),
       ("moved","Run files moved into the merge are gone from the variable."),
       ("two_mut","Merging two runs into one buffer."),
       ("mismatched","Row counts are `usize`, limits and offsets are `i64` in SQL."),
       ("no_eq","A sort key made of several columns needs its own `Ord`.")],
"3h": [("moved","Plan nodes are boxed trees: rewriting one moves it; rebuild instead of reusing the old name."),
       ("non_exhaustive","A `match` over plan node kinds must cover every kind."),
       ("move_out_of_borrow","Taking a child out of a node behind `&mut`: `mem::replace` or rebuild."),
       ("borrow_moved","Moving a node while a reference into it is still held."),
       ("no_method","`Arc<PlanNode>` needs `Arc::as_ref` or deref to reach the node's methods.")],
"4a": [("moved","A transaction handle (`Arc<Transaction>`) moved into a closure: clone the `Arc`."),
       ("not_send","A transaction shared between threads must be `Send + Sync`."),
       ("mismatched","Timestamps are `i64`, ids are `u64`, positions are `usize`."),
       ("read_while_write","Walking an undo chain while appending to the log."),
       ("temp_dropped","`txn.lock().unwrap().logs.last()` returns a reference into a guard that ends with the statement.")],
"4b": [("two_mut","A write touches the table heap and the transaction's write set at once."),
       ("borrow_moved","Moving the transaction while a reference into its undo logs is held."),
       ("moved","An `Arc<Transaction>` moved into the executor: clone it."),
       ("read_while_write","Garbage collection walking the version chains while editing them."),
       ("closure_outlives","Test threads that start transactions need `move` closures.")],
"4c": [("no_method","`sync_all` and `sync_data` are methods of `File`; `Write` and `Read` traits must be imported for the rest."),
       ("mismatched","An LSN is a byte offset: `u64` on disk, `usize` in a `Vec`."),
       ("moved","A log record moved into the buffer is gone from the variable."),
       ("closure_outlives","Crash tests that run recovery on a thread need `move`."),
       ("non_exhaustive","A log record is an enum (begin, change, commit, abort, checkpoint): analysis, redo and undo each `match` over all of them.")],
"4d": [("closure_outlives","Every test thread that takes locks needs a `move` closure with its own `Arc<LockManager>`."),
       ("moved","The lock manager is shared: clone the `Arc`, do not move it into the first thread."),
       ("guard_across","`Condvar::wait` takes your `MutexGuard` and gives a new one back: assign it, in a loop."),
       ("not_send","A `MutexGuard` cannot be sent to another thread; neither can a type that holds one."),
       ("non_exhaustive","Lock modes, isolation levels and phases are enums: a `match` on all three must be complete.")],
"0a": [("no_method","`downcast_ref` and `downcast` belong to `dyn Any`; the value must be `Any + Send + Sync`."),
       ("moved","Path copying clones `Arc`s, not nodes: using an `Arc` after moving it into the new node."),
       ("missing_lifetime","`get` returns a reference into the trie: its lifetime is the trie's."),
       ("not_send","A value stored in a shared trie must be `Send + Sync`.")],
"0b": [("two_mut","Linking a new node between two existing ones borrows both."),
       ("move_out_of_borrow","Removing a node from behind `&mut self` needs `take()`."),
       ("read_while_write","Searching the levels while inserting."),
       ("moved","A node moved into a level's list is gone from the variable.")],
"0c": [("mismatched","The hash is `u64`, the table index is `usize`, the probe distance is `u32`."),
       ("read_while_write","Shifting entries while scanning them."),
       ("not_hash","The key type needs `Hash` and `Eq`."),
       ("no_method","Hashing a key uses `Hasher` and `Hash` traits that must be imported.")],
"0d": [("mismatched","Counters are `u32`, hashes `u64`, error rates `f64`: every mix is a cast you write."),
       ("not_hash","Items to count need `Hash`."),
       ("moved","Merging two sketches consumes one of them unless you borrow."),
       ("type_annot","`collect()` of counters needs the type.")],
}
