# Page data for the challenges whose code was written by hand before the generator existed (code is not generated for these).
def C(id, module, slug, tier, title, diff, tests, learn, concepts, what, why, contract, invariants, relations, examples, checks):
    return dict(id=id, module=module, slug=slug, tier=tier, title=title, diff=diff, tests=tests, learn=learn, concepts=concepts, what=what, why=why,
                contract=contract, invariants=invariants, relations=relations, examples=examples, checks=checks)

CH = [
C("r-c1","00-rust-on-ramp","90-challenge-varint","build","Challenge: a varint codec","easy","stages_r::sr_c1",
  ["designing a compact byte format and its decoder from a written description","telling three kinds of bad input apart"],
  ["bytes-endianness-and-views","errors-as-values-with-result"],
  "Variable-length integers in `src/rust_primer/varint.rs`: `encode_varint` writes a `u64` using as few bytes as it needs, and `decode_varint` reads one back, saying how many bytes it took. The number is cut into groups of 7 bits, lowest group first; each group is one byte, and the high bit of a byte is set when another byte follows.",
  "Databases and protocols are full of small numbers that are sometimes huge: lengths, offsets, counts. A fixed 8 bytes each wastes space; a varint spends one byte on most of them. It is also a compact exercise in reading a format from a description and being strict about bad input.",
  ["`encode_varint(v, out)` appends to `out`, always in the fewest bytes.","`decode_varint(bytes)` returns `(value, bytes_used)` and ignores whatever follows the number.","Bytes that are not one varint are an error, never a panic: `Truncated`, `Overflow` (does not fit in 64 bits) or `NonMinimal` (right number, more bytes than needed)."],
  ["The encoding of `v` has exactly `ceil(bits(v) / 7)` bytes (one for 0).","Every byte but the last has its high bit set; the last has it clear.","`decode(encode(v)) == (v, len)` for every `v`."],
  ["Encoding is monotone in size: a larger number never takes fewer bytes.","Appending any bytes after an encoded number does not change what decodes.","Decoding any byte string either fails with one of the three errors or gives a number whose encoding is exactly the bytes it consumed."],
  ["0 -> [0x00]","127 -> [0x7f]","128 -> [0x80, 0x01]","300 -> [0xac, 0x02]","u64::MAX -> 10 bytes","[0x80, 0x00] -> NonMinimal","[0x80] -> Truncated"],
  ["Exact bytes for the edges 0, 127, 128 and `u64::MAX`.","A property over random numbers: round trip, fewest bytes, trailing bytes untouched.","A property over streams, including streams cut in the middle of a number.","A property over random bytes: no panic, and accepted input re-encodes to what was read."]),
C("r-c2","00-rust-on-ramp","91-challenge-the-long-run","debug","Challenge: the long run","very-easy","stages_r::sr_c2",
  ["finding a bug from a shrunk property-test counterexample"],
  ["property-testing-and-fuzzing","checking-invariants"],
  "`src/rust_primer/rle.rs` has a complete run-length codec: `aaab` becomes the pairs (3, a) (1, b). It looks right, and it has one bug. Find it with the tests, and fix it.",
  "Most real debugging starts from a failing test and a counterexample, not from reading code. A property test that fails prints the *smallest* input it could find that breaks the rule, and that input is usually the whole bug report.",
  ["`rle_encode` turns data into (count, byte) pairs with counts from 1 to 255.","`rle_decode` turns them back and reports a count of 0 or a missing byte as an error."],
  ["Every count in the encoding is between 1 and 255.","The counts add up to the length of the data.","No pair is wider than two bytes."],
  ["`decode(encode(x)) == x` for every `x`.","The encoding is never more than twice the length of the data.","Encoding data made of one repeated byte gives `ceil(len / 255)` pairs."],
  ["[] -> []","\"aaab\" -> [3, a, 1, b]","[7; 255] -> [255, 7]","[7; 256] -> [255, 7, 1, 7]"],
  ["The exact pairs for small inputs and for the longest run one pair can hold.","Round trips of random data, including long runs.","A well-formedness property: counts and lengths.","Bad input to the decoder is an error."]),
C("1a-c1","01-disk-manager","90-challenge-a-mirrored-disk","build","Challenge: a mirrored disk","medium","stages_1a::s1a_c1",
  ["building a component behind a trait from a behavioural description","keeping two copies consistent when one of them fails and comes back"],
  ["ownership-of-files-and-raii","rust-io-errors","model-based-testing"],
  "`MirroredDisk` in `src/storage/disk/mirrored_disk.rs`: a disk made of two other disks that keeps the same pages on both, so that one of them failing does not lose anything. It is a `DiskIo` like the others.",
  "Real storage engines do not trust one device. Mirroring (RAID 1) is the simplest answer, and a test of whether you understand what a disk promises: a disk that fails for a while and comes back has *missed* writes, and a naive mirror will read the old page from it.",
  ["Writes go to both disks; a write succeeds if at least one disk took it, and fails only if both failed.","Reads return the latest successful write of the page (zeros if never written or deleted), even while one disk is down and even if a disk missed writes while it was down.","At most one disk is down at any moment. When a disk comes back, the reads that follow bring it up to date.","Deleting a page deletes it from both."],
  ["With both disks healthy, both copies hold every write.","No read ever returns a page older than the latest successful write.","A write that returns `Ok` is on at least one disk."],
  ["Taking either disk down and reading gives the same bytes as before.","Writing while a disk is down, bringing it back, and then taking the *other* disk down still reads the new page.","The mirror behaves exactly like a plain map of pages."],
  ["write 1; primary down; write 2; primary up; read -> 2 (not 1)","both down; write -> error","delete after write -> zeros"],
  ["A mirror with both disks healthy behaves like one disk.","Reads survive either disk failing; writes survive one disk failing.","A disk that missed a write never serves the old page.","A property over random writes, reads, deletes and failures against a map of pages."]),
C("1a-c2","01-disk-manager","91-challenge-the-stale-read","debug","Challenge: the stale read","easy","stages_1a::s1a_c2",
  ["finding a caching bug from a shrunk counterexample"],
  ["property-testing-and-fuzzing","checking-invariants"],
  "`src/storage/disk/cached_disk.rs` is a complete write-through page cache in front of any disk. It is meant to be invisible: to everyone using it, it behaves exactly like the disk underneath. It looks right, and it has one bug. Find it and fix it.",
  "A cache is a second copy of the truth, and every second copy can go stale. Cache bugs are rarely in the code that reads or writes; they are in the operations that someone forgot to tell the cache about. The same lesson returns with the buffer pool in module 1f.",
  ["A `CachedDisk` answers every read, write and delete exactly as the disk underneath would, whatever its capacity.","It writes through: the disk underneath is always current."],
  ["Every page in the cache equals that page on the disk underneath.","The cache never holds more than its capacity.","A deleted page is in neither."],
  ["Replacing the cache by the plain disk never changes any answer.","A bigger cache never changes answers, only the number of reads that reach the disk."],
  ["write 7; read 7; delete 7; read 7 -> zeros","capacity 2, write pages 0..5, read all -> all correct"],
  ["A page just written is served from memory.","A full cache forgets old pages without losing data.","A deleted page reads as zeros, and cache and disk agree.","A property against a plain map of pages."]),
C("1b-c1","02-disk-scheduler","90-challenge-a-throttled-disk","build","Challenge: a throttled disk","medium","stages_1b::s1b_c1",
  ["building a component behind the DiskIo trait from a behavioural description","a rate limit that is exact when time is injected"],
  ["atomics-ordering-and-the-log","model-based-testing","performance-tests-and-measuring"],
  "`ThrottledDisk` in `src/storage/disk/throttled_disk.rs`: a `DiskIo` that wraps another disk and lets writes through only at a limited rate (a **token bucket**). A write over the limit is refused at once with `ErrorKind::WouldBlock` and never reaches the disk underneath; reads and deletes are never limited. Time comes from a `Clock` you are given, so a test can move it by hand.",
  "A database that can write faster than its disk can take them, or that must leave room for reads, needs a brake. A token bucket is the standard one: constant memory, and it allows the short bursts real workloads have. Building it against an injected clock is also how time-dependent code is made testable: nothing here sleeps.",
  ["The bucket holds up to `burst` tokens and starts full. Tokens are added continuously at `writes_per_second`, never above `burst`. A write takes one whole token.","Partial tokens add up between calls.","Many threads may write at once; together they never get more writes than there are tokens."],
  ["The tokens are always between 0 and `burst`.","The number of writes accepted in any window is at most `burst + rate * window`.","A refused write has no effect on the disk underneath."],
  ["Moving the clock forward never makes a write that was accepted be refused.","Doubling the rate and halving the time between calls gives the same decisions.","After a long idle time exactly `burst` writes are accepted in a row, then none."],
  ["rate 1, burst 3: write, write, write -> ok; write -> WouldBlock","rate 2, burst 1: write ok; +250ms write refused; +250ms write ok"],
  ["A burst goes through and the next write is refused, and it is not on the disk.","Tokens return continuously with time and never beyond the burst.","Reads and deletes are never limited; threads share the bucket correctly.","A property against a model that counts tokens exactly."]),
C("1b-c2","02-disk-scheduler","91-challenge-the-gate","debug","Challenge: the gate","easy","stages_1b::s1b_c2",
  ["finding a concurrency bug from a failing test that waits"],
  ["condvars-and-blocking-queues","deadlock-and-lock-ordering"],
  "`src/common/gate.rs` is a complete one-shot gate: threads wait at it until somebody opens it, and once open it stays open. It looks right, and it has one bug. Find it with the tests and fix it.",
  "A concurrency bug rarely announces itself: the code passes when one thread waits and fails when several do, and the symptom is a program that never finishes, not an error. Learning to read \"something is still waiting\" and ask *who should have woken it* is the skill.",
  ["`wait` returns once the gate is open, for every thread that waits, however many, and for threads that arrive after it was opened.","`open` may be called more than once."],
  ["Once open, a gate is never closed again.","No thread is left waiting at an open gate."],
  ["The number of threads released by `open` equals the number that were waiting, not one.","Waiting after the gate is open returns at once, for any number of callers."],
  ["4 waiters, open -> 4 released","open, then wait -> returns immediately","two gates: opening one releases only its waiters"],
  ["A closed gate holds its waiter; an open one lets everybody through, including late arrivals.","Every waiter goes on, not just one.","Gates are independent."]),
C("1c-c1","03-simple-replacers","90-challenge-least-frequently-used","build","Challenge: least frequently used","easy","stages_1c::s1c_c1",
  ["writing a replacement policy of your own against the FrameReplacer contract","breaking ties in a way a test can check"],
  ["replacement-policies","model-based-testing"],
  "`LfuReplacer` in `src/buffer/lfu_replacer.rs`: a replacement policy that evicts the frame used the **fewest times**; among equal counts the one whose last use is oldest goes first. It plugs in wherever a `FrameReplacer` does.",
  "LRU asks \"which page was used longest ago?\"; LFU asks \"which is used least?\". They disagree exactly where it matters: a long scan of pages each used once pushes a hot page out of an LRU cache, while LFU keeps it.",
  ["A frame met for the first time starts with one access and is **not** evictable; every `record_access` adds one.","`evict` removes and returns the evictable frame with the fewest accesses (oldest last access among equals), or `None`; an evicted or removed frame is forgotten, count included.","`remove` forgets an evictable frame; a known frame that is not evictable panics. `size` counts evictable frames; unknown frames are ignored."],
  ["`size()` equals the number of frames that are known and evictable.","A victim is always an evictable frame.","An evicted frame is no longer known: using it again starts from one access."],
  ["Adding an access to a frame never makes it more likely to be evicted before the others.","Pinning a frame (making it not evictable) never changes any other frame's order."],
  ["accesses: 0,1,2,0,0,1; all evictable -> evict order 2, 1, 0","tie on one access: the one used first goes first"],
  ["Eviction order by count and the tie-break.","New frames are not evictable; pinning again works; forgotten frames restart.","`remove` and its panic.","A property against a plain model of the policy."]),
C("1c-c2","03-simple-replacers","91-challenge-first-in-first-out","debug","Challenge: first in, first out","easy","stages_1c::s1c_c2",
  ["finding a bookkeeping bug from a model-based counterexample"],
  ["replacement-policies","property-testing-and-fuzzing","checking-invariants"],
  "`src/buffer/fifo_replacer.rs` is a complete first-in-first-out policy: the frame that has been in the pool longest is evicted first, however often it was used since. It looks right, and it has one bug. Find it and fix it.",
  "When a structure keeps the same fact in two places (here, which frames are evictable and how many there are), every change has to update both, and the bug is always in the path someone forgot. A property that compares *every* observable after *every* step finds it.",
  ["The victim is the evictable frame that arrived first; using a frame again does not move it.","A frame that is in use is skipped but keeps its place.","`size` is the number of evictable frames, always."],
  ["`size()` equals the number of evictable frames after every call.","Arrival order never changes except by removal."],
  ["Pinning and unpinning a frame never changes the order of the others.","Saying \"evictable\" or \"not evictable\" twice is the same as once."],
  ["arrive 0,1,2; use 0 ten times; evict -> 0","pin 0; evict -> 1; unpin 0; evict -> 0"],
  ["Arrival order beats use; a skipped frame keeps its place.","`size` through every kind of change.","A property against a plain model."]),
C("1d-c1","04-lru-k-replacer","90-challenge-a-cache-simulator","build","Challenge: a cache simulator","medium","stages_1d::s1d_c1",
  ["measuring a replacement policy by replaying a trace","computing the optimal policy as a yardstick"],
  ["replacement-policies","lru-k-and-scan-resistance","performance-tests-and-measuring"],
  "Two functions in `src/buffer/cache_sim.rs`. `simulate` replays a trace of page accesses through a pool of a fixed number of frames, with any `FrameReplacer` choosing victims, and returns the number of hits. `belady_hits` returns the best any policy could do on the trace: Belady's rule evicts the page whose next use is furthest in the future.",
  "\"Which policy is better?\" has no answer without a workload. A simulator turns the question into a number, and the optimum tells you how much room is left. This is how real systems are tuned: from traces of production access patterns.",
  ["A miss with a free frame uses it; a miss with the pool full evicts the replacer's victim and reuses its frame. The replacer sees every access, and every page is evictable as soon as it is used. A capacity of 0 has no hits.","`belady_hits` may look at the whole trace."],
  ["`0 <= hits <= len(trace) - distinct pages used`, at least the first use of each page misses.","Every page in the pool is a page of the trace."],
  ["No policy has more hits than `belady_hits`.","A bigger pool never has fewer hits under the optimal policy.","With capacity at least the number of distinct pages, hits = len - distinct."],
  ["[1,2,3,1,2,3,1,2,3], capacity 3 -> 6 hits","[1,1,2,2,2,1,3], capacity 1 -> 3 hits","[1,2,3,1,2], capacity 2: optimal 1 hit; FIFO 0 hits"],
  ["Small traces worked by hand.","A hot page between a scan, where frequency beats recency.","No policy beats the optimum; a bigger pool never hurts it.","LRU through the simulator equals a one-line model of LRU."]),
C("1d-c2","04-lru-k-replacer","91-challenge-the-distance","debug","Challenge: the distance","easy","stages_1d::s1d_c2",
  ["finding an off-by-one in a bounded history from a definition-based property"],
  ["lru-k-and-scan-resistance","property-testing-and-fuzzing","logical-clocks-and-timestamps"],
  "`src/buffer/k_history.rs` keeps, for one page, the times of its last `k` accesses and answers the backward k-distance: how long ago the k-th most recent access was, or nothing if there have been fewer than `k`. It looks right, and it has one bug. Find it and fix it.",
  "LRU-K lives on this one number, and an error of a single access in it is invisible in a demo and changes which page is evicted in production. Bugs like this are found by writing the definition down in the test as plainly as possible and comparing.",
  ["After any number of accesses, `k_distance(now)` is `now` minus the time of the k-th most recent access, or `None` when fewer than `k` have been recorded.","Only the last `k` accesses are remembered."],
  ["The history never holds more than `k` times.","Times in the history are in increasing order."],
  ["A more recent access never lengthens the distance.","With `k = 1` the distance is the time since the last access.","The distance at `now + d` is the distance at `now` plus `d`."],
  ["k=2, accesses at 1, 5; now 10 -> 9","k=2, accesses at 1, 5, 9; now 10 -> 5","k=3, two accesses -> None"],
  ["No distance before `k` accesses; the distance to the k-th most recent; `k = 1`.","Only the last `k` accesses count.","A property against the definition for any `k` and times."]),
C("2a-c1","08-typed-pages","90-challenge-rank-and-select","build","Challenge: rank and select","easy","stages_2a::s2a_c1",
  ["answering order-statistic queries over a sorted structure with binary search"],
  ["slices-copy-within-and-binary-search","model-based-testing"],
  "`RankedSet` in `src/storage/page/ranked_array.rs`: a set of `u64`s that answers `rank(x)` (how many are smaller) and `select(i)` (the i-th smallest) without looking at every number, plus `count_range(lo, hi)`.",
  "\"How many keys are below this one?\" is the question behind `OFFSET`, percentiles, and range-count estimates in an optimiser. A sorted array answers it with the binary search you wrote for pages; a B+ tree can answer it when each inner entry also remembers how many keys lie below.",
  ["`insert` and `remove` report whether the set changed.","`rank(x)` counts the numbers strictly smaller than `x`, whether or not `x` is in the set.","`select(i)` is the i-th smallest (0 is the smallest) or `None`.","`count_range(lo, hi)` counts numbers in `lo..hi`, 0 when `hi <= lo`."],
  ["The numbers are always in strictly increasing order, no duplicates.","`len()` equals the number of successful inserts minus removes."],
  ["`select(rank(x)) == Some(x)` for every `x` in the set.","`rank(select(i).unwrap()) == i` for every `i < len`.","`count_range(a, b) == rank(b) - rank(a)` for `a < b`.","Inserting `x` raises `rank(y)` by one exactly for `y > x`."],
  ["{10,20,30,40}: rank(15) = 1, rank(10) = 0, rank(41) = 4","select(3) = 40, select(4) = None","count_range(20, 50) = 3"],
  ["Rank and select on small sets, and that they are inverses.","Duplicate inserts, missing removes.","Half-open ranges and reversed ranges.","200 000 ranks over 20 000 numbers finish quickly.","A property against a `BTreeSet`."]),
C("2a-c2","08-typed-pages","91-challenge-the-run-of-equals","debug","Challenge: the run of equals","easy","stages_2a::s2a_c2",
  ["finding a boundary bug in a binary search over duplicates"],
  ["slices-copy-within-and-binary-search","property-testing-and-fuzzing"],
  "`src/storage/page/bound_search.rs` has `lower_bound` and `upper_bound` for a sorted slice that may hold duplicates: the first position a key could be inserted at, and the first position after all its copies. It looks right, and it has one bug. Find it and fix it.",
  "Binary search is the most commonly mis-written algorithm there is, and nearly every mistake is in the boundary: strict or not, which half to keep. Duplicates are where it shows, and a B+ tree with non-unique keys depends on both bounds being exactly right.",
  ["`lower_bound(s, k)` is the first index `i` with `s[i] >= k` (or `len`).","`upper_bound(s, k)` is the first index `i` with `s[i] > k` (or `len`).","`count_of` is the difference."],
  ["`lower_bound <= upper_bound <= len`.","Every element before `lower_bound` is `< k`; every element from `upper_bound` on is `> k`."],
  ["`upper_bound(s, k) == lower_bound(s, k + 1)`.","A key that is absent has equal bounds.","Both equal `partition_point` with `<` and `<=`."],
  ["[1,3,3,3,7], key 3 -> lower 1, upper 4","[1,3,3,7], key 5 -> 3, 3","[5;9], key 5 -> 0, 9"],
  ["The bounds of a run of equal keys.","Absent keys, empty and all-equal slices.","Negative keys and the extremes of `i64`.","A property against `partition_point`."]),
C("2b-c1","09-extendible-hash","90-challenge-linear-hashing","build","Challenge: linear hashing","medium","stages_2b::s2b_c1",
  ["growing a hash table one bucket at a time without a directory"],
  ["extendible-hashing","hash-functions-and-murmur3","model-based-testing"],
  "`LinearHashSet` in `src/container/hash/linear_hash_set.rs`: a hash set that grows **one bucket at a time**, in a fixed order, with no directory at all. The table has `round_size` buckets at the start of a round; buckets already split use hash mod `2 * round_size`; a split takes the next bucket in order, adds a bucket at the end, and moves the keys that now hash there.",
  "Extendible hashing doubles a directory and splits only the full bucket; linear hashing never doubles anything and splits buckets in order, full or not. It trades some overflow for a table that grows smoothly and a lookup that needs no directory, and it is what some real systems use.",
  ["`insert` adds a key (false if present) and splits **one** bucket when the load (keys per bucket) goes over `max_load`.","`bucket_of(key)` is `hash mod round_size`, or `hash mod 2 * round_size` for buckets already split this round.","`remove` and `contains` use the same rule; buckets are never merged."],
  ["Every key is in the bucket `bucket_of` names for it, after every operation.","After an insert, the load is at most `max_load` (up to one split's worth).","`bucket_count` only ever grows, by at most one per insert."],
  ["Inserting a key and then removing it leaves the set as it was (except the buckets).","The set of keys is the same as a `HashSet`'s after any operations.","A split moves only the keys of one bucket."],
  ["1 bucket, max_load 1.0: insert 1 -> 1 bucket; insert 2 -> 2 buckets","500 inserts at max_load 2.0 -> more than 2 buckets, all keys found"],
  ["Keys are found after any number of splits.","One split per insert at most, and the load bound.","Duplicates and removals.","A property against a `HashSet`."]),
C("2b-c2","09-extendible-hash","91-challenge-the-directory","debug","Challenge: the directory","medium","stages_2b::s2b_c2",
  ["finding a bug in the doubling of an extendible hash directory"],
  ["extendible-hashing","checking-invariants"],
  "`src/container/hash/directory_split.rs` is the bookkeeping of an extendible hash directory: which bucket each slot points at, and how deep each bucket is. `split` splits a bucket, doubling the directory first when needed. It looks right, and it has one bug. Find it and fix it.",
  "The directory is a few lines of index arithmetic, and a mistake in it does not crash: it silently sends some keys to the wrong bucket. The invariants of the structure are the only way to catch it, so writing them down is the exercise.",
  ["A directory of `2^global` slots; slot `i` is reached by the low `global` bits of a hash.","A bucket of local depth `d` is pointed at by every slot that agrees with it on its low `d` bits.","`split` raises the bucket's depth by one, creates a new bucket for the slots whose next bit is 1, and doubles the directory first (copying it) when the bucket is as deep as the directory."],
  ["Every local depth is at most the global depth.","A bucket of depth `d` is pointed at by exactly `2^(global - d)` slots, which agree on their low `d` bits.","Every slot points at exactly one bucket."],
  ["Doubling the directory never changes which bucket any hash value goes to.","Splitting bucket `b` changes only the slots that pointed at `b`.","Two hashes that agree on their low `d` bits of a bucket's depth `d` are always in the same bucket."],
  ["new directory: 1 slot, 1 bucket, depth 0","split(0): global 1, 2 buckets, hash 0b10 -> bucket 0, 0b11 -> bucket 1"],
  ["The first split and the doubling.","Splitting a shallow bucket does not double.","After a doubling, buckets are still reached by the slots that agree with them.","A property over random sequences of splits checking every invariant."]),
C("2c-c1","10-b-plus-tree","90-challenge-bulk-loading","build","Challenge: bulk loading","medium","stages_2c::s2c_c1",
  ["planning a B+ tree built bottom-up from sorted keys"],
  ["b-plus-tree-anatomy","splitting-and-promoting","model-based-testing"],
  "`leaf_sizes` and `level_widths` in `src/storage/index/bulk_layout.rs`: when all keys are known and sorted, a B+ tree can be built bottom-up in one pass instead of by `n` inserts and the splits they cause. This is the planning half: how many keys go in each leaf, and how many nodes each level has.",
  "Building an index over an existing table (`CREATE INDEX`) is the common case, and inserting a million keys one at a time does a million root-to-leaf descents and a hundred thousand splits. A bulk load writes each page once, full. The layout rules are small and easy to get subtly wrong at the right-hand edge.",
  ["Leaves hold at most `max` keys; every leaf except a single leaf holds at least `max / 2`.","The leaves are as few as possible and full from the left; if the last would be too small, the last two share their keys, the second to last getting the extra one.","`level_widths` is the node count of each level from the leaves to the root; an inner node has at most `fanout` children."],
  ["The sizes add up to `n`.","Every size is between 1 and `max`, and at least `max / 2` unless there is one leaf.","The last level has exactly one node."],
  ["More keys never need fewer leaves.","`leaf_sizes(n).len() == ceil(n / max)`.","Each level has `ceil(children / fanout)` nodes."],
  ["leaf_sizes(9, 4) = [4, 3, 2]","leaf_sizes(5, 4) = [3, 2]","level_widths(17, 4, 4) = [5, 2, 1]","level_widths(1000, 10, 5) = [100, 20, 4, 1]"],
  ["Exact plans for small cases and the uneven right edge.","Levels up to a single root.","A million keys planned without building anything.","Properties: valid and minimal plans; shrinking levels."]),
C("2c-c2","10-b-plus-tree","91-challenge-the-separator","debug","Challenge: the separator","easy","stages_2c::s2c_c2",
  ["finding a bug in what a node split keeps and what it moves up"],
  ["splitting-and-promoting","routing-with-separator-keys","checking-invariants"],
  "`split_keys` in `src/storage/index/node_split.rs` splits the sorted keys of a full node in two and chooses the separator for the parent. A leaf keeps every key (the separator is a copy of the right node's first key); an inner node moves the separator *up*, so it is in neither node. It looks right, and it has one bug. Find it and fix it.",
  "A wrong split loses or duplicates a key, and the tree still looks plausible until a lookup for that key fails, much later. The difference between leaf and inner splits is the classic place for it.",
  ["The left node gets the first `(len + 1) / 2` keys.","Leaf: separator is the right node's first key, which stays in the right node.","Inner: separator is the first key that would have gone right, and it is in neither node."],
  ["Left keys are all `<` the separator.","Leaf: right keys are all `>=` the separator; inner: right keys are all `>` it.","Nothing is lost or invented."],
  ["Concatenating left, (separator for an inner node), right gives the original keys.","A leaf's two nodes together hold as many keys as before; an inner node's hold one fewer."],
  ["leaf [1,2,3,4] -> ([1,2], 3, [3,4])","inner [10,20,30,40,50] -> ([10,20,30], 40, [50])"],
  ["Leaf and inner splits, odd and even counts.","No key is lost or invented, for all sizes.","A property over random sorted keys."]),
C("2d-c1","11-b-plus-tree-tombstones","90-challenge-the-dead-leaf","debug","Challenge: the dead leaf","easy","stages_2d::s2d_c1",
  ["finding a bug in an iterator that must step over deleted entries"],
  ["range-scans-and-the-leaf-chain","property-testing-and-fuzzing"],
  "`LiveKeys` in `src/storage/index/live_iter.rs` walks a chain of leaves in which deleted keys are left as tombstones and yields the live keys in order. It looks right, and it has one bug. Find it and fix it.",
  "With tombstones, a leaf may be entirely dead, and an iterator that handles tombstones inside a leaf can still mishandle a whole leaf of them. Scans that end early do not fail: they return fewer rows.",
  ["Yield every live key, in order, skipping tombstones, across all leaves.","The iterator stays finished once it is finished."],
  ["Keys are yielded in the order they appear.","No tombstone is ever yielded; no live key is skipped."],
  ["The output equals flattening all leaves and filtering the live slots.","Adding a leaf of only tombstones anywhere does not change the output."],
  ["[[1, x, 3], [4, 5, x]] -> 1, 3, 4, 5","[[1], [x, x, x], [9]] -> 1, 9"],
  ["Tombstones inside a leaf.","A dead leaf in the middle, at the ends, several in a row.","Empty input and empty leaves.","A property against a flat filter."]),
]
