[package]
name = "anneal-cli"
description = "Command-line tools for anneal: validate content, run problems"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "anneal"
path = "src/main.rs"

[dependencies]
anneal-content.workspace = true
anneal-runner.workspace = true
anneal-rules.workspace = true
anyhow.workspace = true
argon2.workspace = true
rand_core.workspace = true
rpassword = "7"
similar = "2"
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tokio.workspace = true
indicatif = "0.17"
clap_complete.workspace = true
pulldown-cmark = { version = "0.13.4", default-features = false }
terminal_size = "0.4.4"
