"""Hand-reviewed technique for every problem outside the NeetCode 150 that the similar-question links can't place.
Same format as ASSIGN_150: slug -> key (or "Pattern:key" when the technique lives in another pattern)."""

REST = {
    # Two Pointers
    "reverse-string": "opposite", "valid-word-abbreviation": "in-place", "merge-strings-alternately": "merge-sorted",
    "merge-sorted-array": "merge-sorted", "merge-two-2d-arrays-by-summing-values": "merge-sorted", "move-zeroes": "in-place",
    "remove-duplicates-from-sorted-array": "in-place", "squares-of-a-sorted-array": "opposite", "assign-cookies": "greedy-pair",
    "sort-array-by-parity": "in-place", "reverse-words-in-a-string-iii": "opposite", "backspace-string-compare": "in-place",
    "check-if-two-string-arrays-are-equivalent": "in-place", "apply-operations-to-an-array": "in-place",
    "strobogrammatic-number": "opposite", "adding-spaces-to-a-string": "simulate", "string-compression": "in-place",
    "remove-duplicates-from-sorted-array-ii": "in-place", "partition-array-according-to-given-pivot": "in-place",
    "rotate-array": "opposite", "number-of-subsequences-that-satisfy-the-given-sum-condition": "pair-count",
    "array-with-elements-not-equal-to-average-of-neighbors": "simulate", "divide-players-into-teams-of-equal-skill": "greedy-pair",
    "boats-to-save-people": "greedy-pair", "k-th-symbol-in-grammar": "simulate", "minimum-time-to-make-rope-colorful": "simulate",
    "rearrange-array-elements-by-sign": "in-place", "bag-of-tokens": "greedy-pair",
    "minimum-length-of-string-after-deleting-similar-ends": "opposite", "sentence-similarity-iii": "opposite",
    "meeting-scheduler": "merge-sorted", "product-of-two-run-length-encoded-arrays": "merge-sorted", "sort-transformed-array": "opposite",
    # Sliding Window
    "contains-duplicate-ii": "fixed-window", "minimum-difference-between-highest-and-lowest-of-k-scores": "window-sort",
    "number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold": "fixed-sum", "grumpy-bookstore-owner": "fixed-sum",
    "find-k-length-substrings-with-no-repeated-characters": "fixed-window", "alternating-groups-ii": "fixed-sum",
    "frequency-of-the-most-frequent-element": "window-sort", "fruit-into-baskets": "at-most-k",
    "minimum-number-of-flips-to-make-the-binary-string-alternating": "fixed-sum", "defuse-the-bomb": "fixed-sum",
    "find-k-closest-elements": "window-sort", "get-equal-substrings-within-budget": "window-max",
    "number-of-substrings-containing-all-three-characters": "count-windows", "binary-subarrays-with-sum": "count-windows",
    "count-number-of-nice-subarrays": "count-windows", "subarray-product-less-than-k": "count-windows",
    "length-of-longest-subarray-with-at-most-k-frequency": "at-most-k",
    "count-subarrays-where-max-element-appears-at-least-k-times": "count-windows",
    "maximum-beauty-of-an-array-after-applying-operation": "window-sort", "take-k-of-each-character-from-left-and-right": "window-min",
    "count-of-substrings-containing-every-vowel-and-k-consonants-ii": "count-windows",
    "longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit": "mono-deque",
    # Stack
    "crawler-log-folder": "simulate-stack", "baseball-game": "simulate-stack", "implement-stack-using-queues": "design-queue-stack",
    "implement-queue-using-stacks": "design-queue-stack", "final-prices-with-a-special-discount-in-a-shop": "mono-stack",
    "make-the-string-great": "simulate-stack", "removing-stars-from-a-string": "simulate-stack", "validate-stack-sequences": "simulate-stack",
    "asteroid-collision": "simulate-stack", "simplify-path": "simulate-stack", "decode-string": "nested", "remove-k-digits": "mono-stack",
    "remove-all-adjacent-duplicates-in-string-ii": "simulate-stack", "reverse-substrings-between-each-pair-of-parentheses": "nested",
    "ternary-expression-parser": "nested", "find-permutation": "mono-stack", "basic-calculator-iii": "calculator",
    "minimum-string-length-after-removing-substrings": "simulate-stack", "clear-digits": "simulate-stack",
    "minimum-add-to-make-parentheses-valid": "matching", "maximum-width-ramp": "mono-stack", "basic-calculator-ii": "calculator",
    "132-pattern": "mono-stack", "flatten-nested-list-iterator": "nested", "sum-of-subarray-minimums": "mono-contrib",
    "maximum-frequency-stack": "aux-stack", "robot-collisions": "simulate-stack", "number-of-visible-people-in-a-queue": "mono-stack",
    "shortest-subarray-with-sum-at-least-k": "Sliding Window:mono-deque", "parsing-a-boolean-expression": "nested", "number-of-atoms": "nested",
    # Binary Search
    "search-insert-position": "insert-pos", "guess-number-higher-or-lower": "classic", "arranging-coins": "by-count",
    "valid-perfect-square": "on-answer", "sqrtx": "on-answer", "missing-number-in-arithmetic-progression": "classic",
    "check-if-a-number-is-majority-element-in-a-sorted-array": "insert-pos", "missing-element-in-sorted-array": "by-count",
    "find-the-index-of-the-large-integer": "classic", "maximum-average-subarray-ii": "on-answer", "single-element-in-a-sorted-array": "classic",
    "find-peak-element": "peak", "successful-pairs-of-spells-and-potions": "insert-pos", "house-robber-iv": "on-answer",
    "minimize-the-maximum-difference-of-pairs": "on-answer", "find-first-and-last-position-of-element-in-sorted-array": "insert-pos",
    "most-beautiful-item-for-each-query": "insert-pos", "random-pick-with-weight": "weighted", "search-suggestions-system": "insert-pos",
    "count-the-number-of-fair-pairs": "insert-pos", "binary-searchable-numbers-in-an-unsorted-array": "classic",
    "leftmost-column-with-at-least-a-one": "classic", "find-k-th-smallest-pair-distance": "on-answer", "find-in-mountain-array": "peak",
    "kth-smallest-product-of-two-sorted-arrays": "on-answer",
    # Trees
    "convert-sorted-array-to-binary-search-tree": "from-traversals", "merge-two-binary-trees": "dfs", "range-sum-of-bst": "bst-walk",
    "leaf-similar-trees": "dfs", "evaluate-boolean-binary-tree": "dfs-return", "binary-tree-longest-consecutive-sequence": "dfs-return",
    "binary-tree-longest-consecutive-sequence-ii": "dfs-return", "maximum-average-subtree": "dfs-return", "find-leaves-of-binary-tree": "dfs-return",
    "two-sum-bsts": "inorder", "largest-bst-subtree": "dfs-return", "clone-n-ary-tree": "dfs", "find-root-of-n-ary-tree": "tree-as-graph",
    "nested-list-weight-sum-ii": "bfs-levels", "create-binary-tree-from-descriptions": "from-traversals", "insert-into-a-binary-search-tree": "bst-edit",
    "delete-node-in-a-bst": "bst-edit", "cousins-in-binary-tree-ii": "bfs-levels", "symmetric-tree": "dfs", "linked-list-in-binary-tree": "dfs",
    "minimum-time-to-collect-all-apples-in-a-tree": "tree-as-graph", "construct-quad-tree": "from-traversals", "check-completeness-of-a-binary-tree": "bfs-levels",
    "maximum-width-of-binary-tree": "bfs-levels", "recover-binary-search-tree": "inorder",
    "construct-binary-tree-from-preorder-and-postorder-traversal": "from-traversals", "unique-binary-search-trees": "catalan",
    "unique-binary-search-trees-ii": "catalan", "number-of-good-leaf-nodes-pairs": "dfs-return", "house-robber-iii": "dfs-return",
    "flip-equivalent-binary-trees": "dfs", "operations-on-tree": "tree-as-graph", "all-possible-full-binary-trees": "catalan",
    "find-bottom-left-tree-value": "bfs-levels", "trim-a-binary-search-tree": "bst-edit", "validate-binary-tree-nodes": "tree-as-graph",
    "find-largest-value-in-each-tree-row": "bfs-levels", "pseudo-palindromic-paths-in-a-binary-tree": "dfs-carry", "even-odd-tree": "bfs-levels",
    "delete-leaves-with-a-given-value": "dfs-edit", "delete-nodes-and-return-forest": "dfs-edit", "distribute-coins-in-binary-tree": "dfs-return",
    "convert-bst-to-greater-tree": "inorder", "inorder-successor-in-bst-ii": "bst-walk", "tree-diameter": "dfs-return",
    "binary-tree-upside-down": "dfs-edit", "recover-a-tree-from-preorder-traversal": "from-traversals",
    # Linked List
    "remove-duplicates-from-sorted-list": "splice", "intersection-of-two-linked-lists": "gap", "plus-one-linked-list": "reverse",
    "print-immutable-linked-list-in-reverse": "reverse", "merge-in-between-linked-lists": "splice", "merge-nodes-in-between-zeros": "splice",
    "find-the-minimum-and-maximum-number-of-nodes-between-critical-points": "splice", "design-linked-list": "design-list",
    "design-browser-history": "design-list", "partition-list": "splice", "rotate-list": "splice", "design-circular-queue": "design-list",
    "split-linked-list-in-parts": "splice", "remove-duplicates-from-an-unsorted-linked-list": "splice",
    # Heap / Priority Queue
    "take-gifts-from-the-richest-pile": "pool", "final-array-state-after-k-multiplication-operations-i": "pool", "high-five": "size-k",
    "minimum-cost-to-connect-sticks": "pool", "campus-bikes": "pool", "least-number-of-unique-integers-after-k-removals": "pool",
    "furthest-building-you-can-reach": "greedy-heap", "minimize-deviation-in-array": "pool", "maximum-subsequence-score": "greedy-heap",
    "single-threaded-cpu": "schedule-sim", "seat-reservation-manager": "pool", "process-tasks-using-servers": "schedule-sim",
    "car-pooling": "schedule-sim", "range-sum-of-sorted-subarray-sums": "Linked List:kway-merge",
    "maximum-transactions-without-negative-balance": "greedy-heap", "path-with-maximum-minimum-value": "Advanced Graphs:dijkstra",
    "maximum-performance-of-a-team": "greedy-heap", "ipo": "greedy-heap", "minimum-cost-to-hire-k-workers": "greedy-heap",
    "number-of-flowers-in-full-bloom": "schedule-sim", "constrained-subsequence-sum": "Sliding Window:mono-deque",
    "find-building-where-alice-and-bob-can-meet": "schedule-sim",
    # Backtracking
    "sum-of-all-subset-xor-totals": "include-exclude", "letter-tile-possibilities": "permute", "restore-ip-addresses": "include-exclude",
    "the-k-th-lexicographical-string-of-all-happy-strings-of-length-n": "construct", "matchsticks-to-square": "partition-k",
    "splitting-a-string-into-descending-consecutive-values": "include-exclude", "construct-smallest-number-from-di-string": "construct",
    "find-unique-binary-string": "construct", "split-a-string-into-the-max-number-of-unique-substrings": "include-exclude",
    "maximum-length-of-a-concatenated-string-with-unique-characters": "include-exclude", "partition-to-k-equal-sum-subsets": "partition-k",
    "the-number-of-beautiful-subsets": "include-exclude", "different-ways-to-add-parentheses": "split-memo",
    "construct-the-lexicographically-largest-valid-sequence": "construct", "strobogrammatic-number-ii": "construct",
    "brace-expansion": "construct", "word-pattern-ii": "construct", "android-unlock-patterns": "construct",
    "maximum-score-words-formed-by-letters": "include-exclude", "word-break-ii": "split-memo", "robot-room-cleaner": "grid",
    # Tries
    "counting-words-with-a-given-prefix": "trie", "remove-sub-folders-from-the-filesystem": "trie", "extra-characters-in-a-string": "trie",
    "design-file-system": "trie", "design-in-memory-file-system": "trie",
    # Graphs
    "verifying-an-alien-dictionary": "simulation", "find-the-town-judge": "degree", "count-servers-that-communicate": "flood",
    "find-champion-ii": "degree", "reorder-routes-to-make-all-paths-lead-to-the-city-zero": "tree-walk", "snakes-and-ladders": "bfs-implicit",
    "open-the-lock": "bfs-implicit", "find-eventual-safe-states": "topo", "course-schedule-iv": "topo", "check-if-move-is-legal": "simulation",
    "shortest-bridge": "multi-bfs", "shortest-path-in-binary-matrix": "bfs-implicit", "find-closest-node-to-given-two-nodes": "tree-walk",
    "shortest-path-with-alternating-colors": "bfs-implicit", "minimum-fuel-cost-to-report-to-the-capital": "tree-walk",
    "minimum-score-of-a-path-between-two-cities": "dsu", "number-of-closed-islands": "border", "number-of-enclaves": "border",
    "regions-cut-by-slashes": "dsu", "minimum-number-of-vertices-to-reach-all-nodes": "degree", "is-graph-bipartite": "bipartite",
    "evaluate-division": "weighted", "shortest-distance-after-road-addition-queries-i": "bfs-implicit", "path-with-maximum-gold": "flood",
    "most-profitable-path-in-a-tree": "tree-walk", "find-the-celebrity": "degree", "kill-process": "tree-walk",
    "all-paths-from-source-lead-to-destination": "topo", "web-crawler": "bfs-implicit", "the-maze": "bfs-implicit",
    "the-maze-ii": "Advanced Graphs:dijkstra", "minimum-knight-moves": "bfs-implicit", "the-maze-iii": "Advanced Graphs:dijkstra",
    "nested-list-weight-sum": "tree-walk", "maximum-number-of-points-from-grid-queries": "Advanced Graphs:dijkstra",
    "maximum-number-of-k-divisible-components": "tree-walk", "sliding-puzzle": "bfs-implicit", "largest-color-value-in-a-directed-graph": "topo",
    "minimum-number-of-days-to-eat-n-oranges": "bfs-implicit", "find-all-people-with-secret": "dsu",
    # Advanced Graphs
    "trapping-rain-water-ii": "dijkstra", "minimum-obstacle-removal-to-reach-corner": "dijkstra",
    "minimum-cost-to-make-at-least-one-valid-path-in-a-grid": "dijkstra", "minimum-time-to-visit-a-cell-in-a-grid": "dijkstra",
    "minimum-cost-to-convert-string-i": "floyd", "sequence-reconstruction": "Graphs:topo", "making-a-large-island": "Graphs:flood",
    "minimum-cost-walk-in-weighted-graph": "Graphs:dsu", "number-of-good-paths": "Graphs:dsu", "maximum-employees-to-be-invited-to-a-meeting": "cycles",
    "remove-max-number-of-edges-to-keep-graph-fully-traversable": "Graphs:dsu", "minimum-number-of-days-to-disconnect-island": "articulation",
    "find-minimum-diameter-after-merging-two-trees": "Graphs:tree-walk", "find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree": "mst",
    "bus-routes": "Graphs:bfs-implicit", "build-a-matrix-with-conditions": "Graphs:topo", "greatest-common-divisor-traversal": "Graphs:dsu",
    "divide-nodes-into-the-maximum-number-of-groups": "Graphs:bipartite",
    # 1-D Dynamic Programming
    "4-keys-keyboard": "recurrence", "handshakes-that-dont-cross": "Trees:catalan", "triangle": "2-D Dynamic Programming:grid-dp",
    "filling-bookcase-shelves": "partition-dp", "combination-sum-iv": "unbounded", "perfect-squares": "unbounded",
    "check-if-there-is-a-valid-partition-for-the-array": "take-skip", "maximum-subarray-min-product": "Stack:mono-stack", "integer-break": "recurrence",
    "stickers-to-spell-word": "bitmask", "uncrossed-lines": "2-D Dynamic Programming:two-string", "ugly-number-ii": "recurrence",
    "new-21-game": "recurrence", "best-team-with-no-conflicts": "lis", "longest-string-chain": "lis", "knight-dialer": "count-states",
    "partition-array-for-maximum-sum": "partition-dp", "largest-divisible-subset": "lis", "count-strictly-increasing-subarrays": "recurrence",
    "sentence-screen-fitting": "recurrence", "stone-game-iii": "game", "concatenated-words": "prefix-dp", "maximize-score-after-n-operations": "bitmask",
    "count-all-valid-pickup-and-delivery-options": "recurrence", "number-of-ways-to-divide-a-long-corridor": "take-skip",
    "maximum-sum-of-3-non-overlapping-subarrays": "take-skip", "maximum-profit-in-job-scheduling": "take-skip", "student-attendance-record-ii": "count-states",
    "optimal-account-balancing": "bitmask", "valid-palindrome-iii": "2-D Dynamic Programming:two-string",
    "encode-string-with-shortest-length": "2-D Dynamic Programming:interval",
    # 2-D Dynamic Programming
    "length-of-longest-fibonacci-subsequence": "pair-dp", "last-stone-weight-ii": "1-D Dynamic Programming:subset",
    "stone-game": "1-D Dynamic Programming:game", "stone-game-ii": "1-D Dynamic Programming:game", "maximal-square": "grid-dp",
    "count-square-submatrices-with-all-ones": "grid-dp", "ones-and-zeroes": "1-D Dynamic Programming:subset", "2-keys-keyboard": "1-D Dynamic Programming:recurrence",
    "maximum-alternating-subsequence-sum": "state-machine", "number-of-dice-rolls-with-target-sum": "1-D Dynamic Programming:count-states",
    "minimum-falling-path-sum": "grid-dp", "out-of-boundary-paths": "1-D Dynamic Programming:count-states", "longest-ideal-subsequence": "1-D Dynamic Programming:lis",
    "count-number-of-teams": "1-D Dynamic Programming:lis", "count-vowels-permutation": "1-D Dynamic Programming:count-states",
    "number-of-ways-to-rearrange-sticks-with-k-sticks-visible": "1-D Dynamic Programming:count-states", "flip-string-to-monotone-increasing": "state-machine",
    "number-of-music-playlists": "1-D Dynamic Programming:count-states", "number-of-ways-to-form-a-target-string-given-a-dictionary": "1-D Dynamic Programming:count-states",
    "profitable-schemes": "1-D Dynamic Programming:subset", "minimum-cost-to-cut-a-stick": "interval", "painting-the-walls": "1-D Dynamic Programming:subset",
    "number-of-ways-to-stay-in-the-same-place-after-some-steps": "1-D Dynamic Programming:count-states", "string-compression-ii": "1-D Dynamic Programming:partition-dp",
    "minimum-difficulty-of-a-job-schedule": "1-D Dynamic Programming:partition-dp", "arithmetic-slices-ii-subsequence": "pair-dp",
    "k-inverse-pairs-array": "1-D Dynamic Programming:count-states", "cherry-pickup-ii": "grid-dp", "minimum-falling-path-sum-ii": "grid-dp",
    "freedom-trail": "two-string", "split-array-with-same-average": "1-D Dynamic Programming:subset", "paint-house-ii": "grid-dp",
    # Greedy
    "buy-two-chocolates": "sort-pick", "lemonade-change": "scan-balance", "minimum-number-of-moves-to-seat-everyone": "sort-pick",
    "maximum-odd-binary-number": "swap-greedy", "maximum-nesting-depth-of-the-parentheses": "scan-balance",
    "check-if-one-string-swap-can-make-strings-equal": "count-greedy", "how-many-apples-can-you-put-into-the-basket": "sort-pick",
    "minimum-operations-to-make-binary-array-elements-equal-to-one-i": "flip-window", "buildings-with-an-ocean-view": "Stack:mono-stack",
    "minimum-length-of-string-after-operations": "count-greedy", "construct-k-palindrome-strings": "count-greedy",
    "separate-black-and-white-balls": "scan-balance", "minimum-increment-to-make-array-unique": "sort-pick", "maximum-sum-circular-subarray": "kadane",
    "minimum-swaps-to-group-all-1s-together-ii": "Sliding Window:fixed-sum", "minimum-number-of-changes-to-make-binary-string-beautiful": "scan-balance",
    "minimize-maximum-of-array": "Binary Search:on-answer", "maximize-ysum-by-picking-a-triplet-of-distinct-xvalues": "Heap / Priority Queue:greedy-heap",
    "minimum-difference-between-largest-and-smallest-value-in-three-moves": "sort-pick", "maximum-total-importance-of-roads": "sort-pick",
    "minimum-number-of-pushes-to-type-word-ii": "count-greedy", "dota2-senate": "simulate-greedy",
    "maximum-points-you-can-obtain-from-cards": "Sliding Window:fixed-sum", "eliminate-maximum-number-of-monsters": "sort-pick",
    "two-city-scheduling": "sort-pick", "maximum-length-of-pair-chain": "Intervals:by-end", "best-sightseeing-pair": "scan-balance",
    "make-lexicographically-smallest-array-by-swapping-elements": "Graphs:dsu", "minimum-deletions-to-make-character-frequencies-unique": "count-greedy",
    "minimum-deletions-to-make-string-balanced": "scan-balance", "candy": "scan-balance", "remove-colored-pieces-if-both-neighbors-are-the-same-color": "count-greedy",
    "maximum-score-from-removing-substrings": "Stack:simulate-stack", "maximum-element-after-decreasing-and-rearranging": "sort-pick",
    "number-of-laser-beams-in-a-bank": "scan-balance", "reveal-cards-in-increasing-order": "simulate-greedy",
    "construct-string-with-repeat-limit": "Heap / Priority Queue:greedy-heap", "find-valid-matrix-given-row-and-column-sums": "scan-balance",
    "score-after-flipping-matrix": "swap-greedy", "flip-columns-for-maximum-number-of-equal-rows": "count-greedy", "maximum-matrix-sum": "count-greedy",
    "make-two-arrays-equal-by-reversing-subarrays": "count-greedy", "shortest-subarray-to-be-removed-to-make-array-sorted": "Two Pointers:opposite",
    "max-chunks-to-make-sorted": "scan-balance", "next-permutation": "swap-greedy", "maximum-swap": "swap-greedy",
    "maximal-score-after-applying-k-operations": "Heap / Priority Queue:pool", "maximum-frequency-after-subarray-operation": "kadane",
    "put-boxes-into-the-warehouse-i": "sort-pick", "put-marbles-in-bags": "sort-pick", "minimum-number-of-k-consecutive-bit-flips": "flip-window",
    "maximum-score-of-a-good-subarray": "Stack:mono-stack", "find-the-maximum-sum-of-node-values": "count-greedy",
    "minimum-number-of-increments-on-subarrays-to-form-a-target-array": "scan-balance", "apply-operations-to-maximize-score": "Stack:mono-contrib",
    # Intervals
    "missing-ranges": "merge", "remove-interval": "merge", "remove-covered-intervals": "merge", "the-number-of-the-smallest-unoccupied-chair": "sweep",
    "check-if-grid-can-be-cut-into-sections": "merge", "my-calendar-i": "calendar", "my-calendar-ii": "calendar", "data-stream-as-disjoint-intervals": "calendar",
    # Math & Geometry
    "excel-sheet-column-title": "number-format", "greatest-common-divisor-of-strings": "number-theory", "insert-greatest-common-divisors-in-linked-list": "number-theory",
    "count-odd-numbers-in-an-interval-range": "formula", "matrix-diagonal-sum": "matrix-sim", "calculate-money-in-leetcode-bank": "formula",
    "largest-odd-number-in-string": "number-format", "transpose-matrix": "matrix-sim", "image-smoother": "matrix-sim", "count-of-matches-in-tournament": "formula",
    "water-bottles": "formula", "largest-local-values-in-a-matrix": "matrix-sim", "power-of-four": "Bit Manipulation:bit-count", "lucky-numbers-in-a-matrix": "matrix-sim",
    "armstrong-number": "number-format", "count-substrings-with-only-one-distinct-letter": "formula", "guess-the-majority-in-a-hidden-array": "Arrays & Hashing:counting",
    "maximum-number-of-ones": "Greedy:sort-pick", "max-points-on-a-line": "point-counts", "magic-squares-in-grid": "matrix-sim", "palindrome-number": "number-format",
    "convert-1d-array-into-2d-array": "matrix-sim", "shift-2d-grid": "matrix-sim", "roman-to-integer": "number-format", "integer-to-roman": "number-format",
    "find-the-punishment-number-of-an-integer": "Backtracking:include-exclude", "check-if-number-is-a-sum-of-powers-of-three": "formula",
    "robot-bounded-in-circle": "matrix-sim", "walking-robot-simulation": "matrix-sim", "zigzag-conversion": "matrix-sim", "rotating-the-box": "matrix-sim",
    "sum-of-square-numbers": "Two Pointers:opposite", "find-missing-observations": "formula", "minimum-time-difference": "Greedy:sort-pick",
    "minimum-operations-to-make-a-uni-value-grid": "median", "largest-submatrix-with-rearrangements": "Greedy:sort-pick",
    "widest-vertical-area-between-two-points-containing-no-points": "Greedy:sort-pick", "tuple-with-same-product": "Arrays & Hashing:counting",
    "lexicographical-numbers": "lex-order", "find-the-winner-of-the-circular-game": "formula", "count-total-number-of-colored-cells": "formula",
    "prime-subtraction-operation": "number-theory", "closest-prime-numbers-in-range": "number-theory", "distribute-candies-among-children-ii": "formula",
    "line-reflection": "point-counts", "minimum-factorization": "number-theory", "minimum-one-bit-operations-to-make-integers-zero": "Bit Manipulation:shift",
    "k-th-smallest-in-lexicographical-order": "lex-order", "integer-to-english-words": "number-format", "best-meeting-point": "median",
    # Bit Manipulation
    "count-triplets-with-even-xor-set-bits-i": "bit-count", "add-binary": "add-bits", "minimum-bit-flips-to-convert-number": "xor", "shuffle-the-array": "shift",
    "add-to-array-form-of-integer": "Math & Geometry:digits", "bitwise-xor-of-all-pairings": "xor", "largest-combination-with-bitwise-and-greater-than-zero": "bit-count",
    "xor-queries-of-a-subarray": "prefix-xor", "maximum-xor-for-each-query": "prefix-xor", "neighboring-bitwise-xor": "xor",
    "shortest-subarray-with-or-at-least-k-ii": "Sliding Window:window-min", "bitwise-and-of-numbers-range": "shift", "find-kth-bit-in-nth-binary-string": "shift",
    "count-triplets-that-can-form-two-arrays-of-equal-xor": "prefix-xor", "minimum-array-end": "shift", "find-if-array-can-be-sorted": "bit-count",
    "longest-subarray-with-maximum-bitwise-and": "Greedy:scan-balance", "longest-nice-subarray": "Sliding Window:window-max",
    "find-the-longest-substring-containing-vowels-in-even-counts": "prefix-xor", "minimize-xor": "shift", "ip-to-cidr": "shift",
    # Arrays & Hashing
    "concatenation-of-array": "simulation",
    "score-of-a-string": "simulation",
    "length-of-last-word": "simulation",
    "valid-word-square": "simulation",
    "confusing-number": "simulation",
    "single-row-keyboard": "simulation",
    "perform-string-shifts": "simulation",
    "sparse-matrix-multiplication": "simulation",
    "candy-crush": "simulation",
    "one-edit-distance": "simulation",
    "number-of-senior-citizens": "simulation",
    "max-consecutive-ones": "simulation",
    "longest-common-prefix": "simulation",
    "longest-strictly-increasing-or-strictly-decreasing-subarray": "simulation",
    "maximum-ascending-subarray-sum": "simulation",
    "special-array-i": "simulation",
    "check-if-array-is-sorted-and-rotated": "simulation",
    "monotonic-array": "simulation",
    "largest-3-same-digit-number-in-string": "simulation",
    "circular-sentence": "simulation",
    "minimum-changes-to-make-alternating-binary-string": "simulation",
    "number-of-students-unable-to-eat-lunch": "simulation",
    "time-needed-to-buy-tickets": "simulation",
    "array-transformation": "simulation",
    "average-waiting-time": "simulation",
    "push-dominoes": "simulation",
    "non-decreasing-array": "simulation",
    "sign-of-the-product-of-an-array": "simulation",
    "number-of-zero-filled-subarrays": "simulation",
    "sequential-digits": "simulation",
    "count-unguarded-cells-in-the-grid": "simulation",
    "split-concatenated-strings": "simulation",
    "text-justification": "simulation",
    "number-of-ships-in-a-rectangle": "simulation",
    "time-taken-to-cross-the-door": "simulation",
    "replace-elements-with-greatest-element-on-right-side": "prefix",
    "maximum-distance-in-arrays": "prefix",
    "range-sum-query-immutable": "prefix",
    "maximum-score-after-splitting-a-string": "prefix",
    "count-vowel-strings-in-ranges": "prefix",
    "range-sum-query-2d-immutable": "prefix",
    "minimum-number-of-operations-to-move-all-balls-to-each-box": "prefix",
    "grid-game": "prefix",
    "shifting-letters-ii": "prefix",
    "minimum-penalty-for-a-shop": "prefix",
    "sum-of-absolute-differences-in-a-sorted-array": "prefix",
    "range-sum-query-2d-mutable": "prefix",
    "find-anagram-mappings": "complement",
    "number-of-good-pairs": "complement",
    "largest-substring-between-two-equal-characters": "complement",
    "shortest-word-distance": "complement",
    "number-of-pairs-of-interchangeable-rectangles": "complement",
    "sentence-similarity": "seen-set",
    "counting-elements": "seen-set",
    "unique-email-addresses": "seen-set",
    "count-the-number-of-consistent-strings": "seen-set",
    "destination-city": "seen-set",
    "path-crossing": "seen-set",
    "intersection-of-two-arrays": "seen-set",
    "find-the-difference-of-two-arrays": "seen-set",
    "largest-unique-number": "counting",
    "lonely-pixel-i": "counting",
    "find-smallest-common-element-in-all-rows": "counting",
    "maximum-difference-between-even-and-odd-frequency-i": "counting",
    "kth-distinct-string-in-an-array": "counting",
    "maximum-number-of-balloons": "counting",
    "find-lucky-integer-in-an-array": "counting",
    "find-words-that-can-be-formed-by-characters": "counting",
    "ransom-note": "counting",
    "redistribute-characters-to-make-all-strings-equal": "counting",
    "find-common-characters": "counting",
    "brick-wall": "counting",
    "unique-length-3-palindromic-subsequences": "counting",
    "uncommon-words-from-two-sentences": "counting",
    "word-subsets": "counting",
    "convert-an-array-into-a-2d-array-with-conditions": "counting",
    "minimum-number-of-operations-to-make-array-empty": "counting",
    "design-compressed-string-iterator": "design-hash",
    "logger-rate-limiter": "design-hash",
    "moving-average-from-data-stream": "design-hash",
    "first-unique-number": "design-hash",
    "design-tic-tac-toe": "design-hash",
    "design-snake-game": "design-hash",
    "zigzag-iterator": "design-hash",
    "design-a-leaderboard": "design-hash",
    "design-hashset": "design-hash",
    "design-hashmap": "design-hash",
    "encode-and-decode-tinyurl": "design-hash",
    "insert-delete-getrandom-o1": "design-hash",
    "design-parking-system": "design-hash",
    "design-underground-system": "design-hash",
    "design-a-food-rating-system": "design-hash",
    "design-hit-counter": "design-hash",
    "shortest-word-distance-ii": "design-hash",
    "dot-product-of-two-sparse-vectors": "design-hash",
    "design-phone-directory": "design-hash",
    "design-log-storage-system": "design-hash",
    "isomorphic-strings": "signature",
    "word-pattern": "signature",
    "analyze-user-website-visit-pattern": "signature",
    "naming-a-company": "signature",
    "find-all-numbers-disappeared-in-an-array": "index-marks",
    "find-missing-and-repeated-values": "index-marks",
    "set-mismatch": "index-marks",
    "find-all-duplicates-in-an-array": "index-marks",
    "first-missing-positive": "index-marks",
    "majority-element": "majority-vote",
    "majority-element-ii": "majority-vote",
    "minimum-index-of-a-valid-split": "majority-vote",
    "height-checker": "sorting",
    "maximum-product-difference-between-two-pairs": "sorting",
    "sort-an-array": "sorting",
    "sort-colors": "sorting",
    "relative-sort-array": "sorting",
    "custom-sort-string": "sorting",
    "wiggle-sort": "sorting",
    "largest-number": "sorting",
    "divide-array-into-arrays-with-max-difference": "sorting",
    "sort-the-jumbled-numbers": "sorting",
    "find-polygon-with-the-largest-perimeter": "sorting",
    "string-matching-in-an-array": "string-match",
    "find-the-index-of-the-first-occurrence-in-a-string": "string-match",
    "repeated-dna-sequences": "string-match",
    "check-if-a-string-contains-all-binary-codes-of-size-k": "string-match",
    "shortest-palindrome": "string-match",
    "number-of-sub-arrays-with-odd-sum": "prefix-map",
    "contiguous-array": "prefix-map",
    "number-of-submatrices-that-sum-to-target": "prefix-map",
    "is-subsequence": "Two Pointers:merge-sorted",
    "append-characters-to-string-to-make-subsequence": "Two Pointers:merge-sorted",
    "shortest-way-to-form-string": "Two Pointers:merge-sorted",
    "reverse-words-in-a-string-ii": "Two Pointers:opposite",
    "remove-element": "Two Pointers:in-place",
    "pascals-triangle": "1-D Dynamic Programming:recurrence",
    "pascals-triangle-ii": "1-D Dynamic Programming:recurrence",
    "can-place-flowers": "Greedy:scan-balance",
    "next-greater-element-i": "Stack:mono-stack",
    "special-array-with-x-elements-greater-than-or-equal-x": "Binary Search:on-answer",
    "best-time-to-buy-and-sell-stock-ii": "Greedy:scan-balance",
    "minimum-number-of-swaps-to-make-the-string-balanced": "Greedy:scan-balance",
    "maximum-product-of-the-length-of-two-palindromic-subsequences": "1-D Dynamic Programming:bitmask",
    "optimal-partition-of-string": "Greedy:last-seen",
    "champagne-tower": "2-D Dynamic Programming:grid-dp",
    "minimum-remove-to-make-valid-parentheses": "Stack:matching",
    "find-the-length-of-the-longest-common-prefix": "Tries:trie",
    "brightest-position-on-street": "Intervals:sweep",
    "apply-substitutions": "Graphs:topo",
    "the-earliest-moment-when-everyone-become-friends": "Graphs:dsu",
    "synonymous-sentences": "Graphs:dsu",
    "design-excel-sum-formula": "Graphs:topo",
    # Corrections to what the similar-question links suggested
    "divide-array-into-equal-pairs": "Arrays & Hashing:counting", "first-unique-character-in-a-string": "Arrays & Hashing:counting",
    "sort-the-people": "Arrays & Hashing:sorting", "sort-array-by-increasing-frequency": "Arrays & Hashing:sorting",
    "find-pivot-index": "Arrays & Hashing:prefix", "subarray-sum-equals-k": "Arrays & Hashing:prefix-map",
    "subarray-sums-divisible-by-k": "Arrays & Hashing:prefix-map", "make-sum-divisible-by-p": "Arrays & Hashing:prefix-map",
    "continuous-subarray-sum": "Arrays & Hashing:prefix-map", "number-of-ways-to-split-array": "Arrays & Hashing:prefix",
    "find-all-anagrams-in-a-string": "Sliding Window:fixed-window", "combinations": "Backtracking:include-exclude", "permutations-ii": "Backtracking:skip-dups",
    "number-of-islands-ii": "Graphs:dsu", "palindrome-linked-list": "Linked List:fast-slow", "remove-linked-list-elements": "Linked List:splice",
    "middle-of-the-linked-list": "Linked List:fast-slow", "delete-n-nodes-after-m-nodes-of-a-linked-list": "Linked List:splice",
    "insert-into-a-sorted-circular-linked-list": "Linked List:splice", "maximum-twin-sum-of-a-linked-list": "Linked List:fast-slow",
    "delete-nodes-from-linked-list-present-in-array": "Linked List:splice", "swapping-nodes-in-a-linked-list": "Linked List:gap",
    "insertion-sort-list": "Linked List:splice", "ugly-number": "Math & Geometry:number-theory", "count-primes": "Math & Geometry:number-theory",
    "longest-substring-with-at-most-two-distinct-characters": "Sliding Window:at-most-k", "longest-substring-with-at-most-k-distinct-characters": "Sliding Window:at-most-k",
    "find-the-power-of-k-size-subarrays-i": "Sliding Window:fixed-sum", "maximum-sum-of-distinct-subarrays-with-length-k": "Sliding Window:fixed-window",
    "subarrays-with-k-different-integers": "Sliding Window:count-windows", "minimum-number-of-operations-to-make-array-continuous": "Sliding Window:window-sort",
    "binary-tree-inorder-traversal": "Trees:inorder", "binary-tree-preorder-traversal": "Trees:inorder", "binary-tree-postorder-traversal": "Trees:inorder",
    "n-ary-tree-postorder-traversal": "Trees:dfs", "path-sum": "Trees:dfs-carry", "closest-binary-search-tree-value": "Trees:bst-walk",
    "count-univalue-subtrees": "Trees:dfs-return", "boundary-of-binary-tree": "Trees:dfs", "verify-preorder-sequence-in-binary-search-tree": "Trees:bst-walk",
    "closest-binary-search-tree-value-ii": "Trees:inorder", "lowest-common-ancestor-of-a-binary-tree": "Trees:dfs-return",
    "lowest-common-ancestor-of-a-binary-tree-iii": "Trees:tree-as-graph", "reverse-odd-levels-of-binary-tree": "Trees:bfs-levels",
    "kth-largest-sum-in-a-binary-tree": "Trees:bfs-levels", "minimum-distance-between-bst-nodes": "Trees:inorder",
    "time-needed-to-inform-all-employees": "Trees:tree-as-graph", "sum-root-to-leaf-numbers": "Trees:dfs-carry", "binary-search-tree-iterator": "Trees:inorder",
    "smallest-string-starting-from-leaf": "Trees:dfs-carry", "step-by-step-directions-from-a-binary-tree-node-to-another": "Trees:tree-as-graph",
    "convert-binary-search-tree-to-sorted-doubly-linked-list": "Trees:inorder", "count-prefix-and-suffix-pairs-i": "Tries:trie",
    "sum-of-prefix-scores-of-strings": "Tries:trie", "count-prefix-and-suffix-pairs-ii": "Tries:trie", "two-sum-less-than-k": "Two Pointers:opposite",
    "4sum": "Two Pointers:ksum", "paint-house": "2-D Dynamic Programming:grid-dp", "paint-fence": "1-D Dynamic Programming:count-states",
    "coin-path": "1-D Dynamic Programming:recurrence", "minimum-cost-for-tickets": "1-D Dynamic Programming:recurrence",
}
