#!/usr/bin/env python3
"""Writes docs/DSA_LEARN_PAGE_STATUS.md: per topic, how many technique cards the Learn page has, how many problems sit under
them, and how many technique names are still only listed at the bottom (docs/DSA_LEARN_PAGE_SPEC.md section 7).

    python3 tools/neetcode/learn_status.py
"""
import json
import tomllib
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
DSA = ROOT / "content" / "dsa"


IDIOMS = ("core implementation", "pitfalls", "overflow and precision", "memoisation versus", "trie versus", "o(1)-space", "space optimisation")


def is_idiom(group):
    g = group.lower()
    return any(g.startswith(x) for x in IDIOMS)


def main():
    problems = json.loads((DSA / "problems.json").read_text())["problems"]
    practice = json.loads((DSA / "practice.json").read_text())["problems"]
    rows, totals = [], Counter()
    for f in sorted((DSA / "lessons").glob("*.toml")):
        d = tomllib.loads(f.read_text())
        pat = d["pattern"]
        techs, extras = d["technique"], d.get("extra", [])
        in_list = [p for p in problems if p["pattern"] == pat]
        out_list = [p for p in practice if p["pattern"] == pat]
        examples = {s for e in extras for s in e.get("examples", [])}
        variants = sum(len(t.get("variant", [])) + 1 for t in techs + extras)
        listed = len(d.get("listed", []))
        idioms = sum(1 for l in d.get("listed", []) if is_idiom(l["group"]))
        row = {
            "pattern": pat, "techniques": len(techs), "extras": len(extras), "cards": len(techs) + len(extras), "templates": variants,
            "list_problems": len(in_list), "other_problems": len(out_list), "examples": len(examples), "listed": listed, "idioms": idioms,
        }
        rows.append(row)
        for k, v in row.items():
            if k != "pattern":
                totals[k] += v
    out = ["# The Learn page: status", "",
           "Generated by `python3 tools/neetcode/learn_status.py`; do not edit by hand. The rules are in [DSA_LEARN_PAGE_SPEC.md](DSA_LEARN_PAGE_SPEC.md).", "",
           "A **card** is a technique with a tested Python implementation (signals, template tabs, traps) and its problems on the right. A "
           "**template** is one tab of a card (a card has one or more). **Names only** are techniques that are named at the bottom of the "
           "page because no card has been written for them yet.", "",
           "| topic | cards | from the lists | extra | templates | list problems | other problems | names only |", "|---|---:|---:|---:|---:|---:|---:|---:|"]
    for r in rows:
        out.append(f"| {r['pattern']} | {r['cards']} | {r['techniques']} | {r['extras']} | {r['templates']} | {r['list_problems']} | {r['other_problems']} | {r['listed']} |")
    out.append(f"| **all** | **{totals['cards']}** | {totals['techniques']} | {totals['extras']} | {totals['templates']} | {totals['list_problems']} | {totals['other_problems']} | {totals['listed']} |")
    out += ["", "## What is still to do", "",
            f"- {totals['listed']} technique names have no card, of which {totals['idioms']} are idioms and pitfalls (implementation habits, "
            "edge cases, space tricks) that are named but would not make a card of their own. The rest are techniques: each is written the same way: signals, a template that passes a behaviour test "
            "against a brute force (`tools/neetcode/lesson_tests.py`), traps, and free LeetCode problems with companies and topic tags.",
            "- Every problem has a key insight (content/dsa/insights.json, DSA_LEARN_PAGE_SPEC.md section 8); a new catalog problem needs its sentence.", ""]
    (ROOT / "docs" / "DSA_LEARN_PAGE_STATUS.md").write_text("\n".join(out))
    print(f"{totals['cards']} cards, {totals['templates']} templates, {totals['listed']} names only")


main()
