#!/usr/bin/env python3
"""Turn a mockup's <style> into an app stylesheet, so the app uses the mockup's own CSS rather than an approximation of it.

- Every class gets a prefix, and every rule is scoped under `.<prefix>root`, so nothing can collide with the app's own styles or leak into other pages.
- The mock's own chrome (its toolbar, its explanatory notes, its page reset) is dropped; the colour tokens stay in the app's design.css.
- The mock's fixed 46px toolbar offset becomes `var(--<prefix>off)` (the app's real header height), set by the page that uses it.

Usage: tools/port_mockup_css.py docs/mockups/course-motion.html web/src/styles/mock-course.css k- [accent-token]
"""
import re, sys

src, dst, prefix = sys.argv[1], sys.argv[2], sys.argv[3]
# Optional fourth argument: the mock's accent colour (`vio`), which becomes `var(--<prefix>ac)` / `var(--<prefix>acb)` so the page can pick its own accent.
accent = sys.argv[4] if len(sys.argv) > 4 else None
html = open(src).read()
css = re.search(r"<style>(.*?)</style>", html, re.S).group(1)
css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)


def blocks(text):
    """Top-level rules of `text`, each as (prelude, body)."""
    out, depth, start, pre = [], 0, 0, ""
    for i, c in enumerate(text):
        if c == "{":
            if depth == 0:
                pre = text[start:i].strip()
                start = i + 1
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                out.append((pre, text[start:i]))
                start = i + 1
    return out


def split_selectors(sel):
    parts, depth, cur = [], 0, ""
    for c in sel:
        if c in "([":
            depth += 1
        if c in ")]":
            depth -= 1
        if c == "," and depth == 0:
            parts.append(cur.strip())
            cur = ""
        else:
            cur += c
    if cur.strip():
        parts.append(cur.strip())
    return parts


MOCK_ONLY = re.compile(r"^(\.top\b|\.bar\b|\.screen\b|\.notes\b|\*|body|html|:root|:focus-visible)")
STATE = (f".{prefix}motion", f".{prefix}motion-off")
keyframes = set(re.findall(r"@keyframes\s+([\w-]+)", css))


def cls(text):
    return re.sub(r"\.([A-Za-z][\w-]*)", lambda m: "." + prefix + m.group(1), text)


def scope(sel):
    s = cls(sel)
    if s.startswith(STATE):
        return f".{prefix}root{s}"  # the mode class sits on the root itself
    if re.match(r"[a-z]", s) and not re.search(r"[.#\[:]", s):
        # A bare element rule (button, h1, kbd...) is only a default: it must not outrank the app's own classes inside the page.
        return f":where(.{prefix}root {s})"
    return f".{prefix}root {s}"


def anim(decl):
    for k in keyframes:
        decl = re.sub(rf"(?<![\w-]){k}(?![\w-])", prefix + k, decl)
    return decl


def declarations(body):
    body = re.sub(r"animation(?:-name)?\s*:[^;}]*", lambda m: anim(m.group(0)), body)
    # Only where the 46px is the toolbar offset (a position or a viewport calc), not any 46px size.
    body = re.sub(r"(top:|inset:|- )46px", lambda m: m.group(1) + f"var(--{prefix}off)", body)
    if accent:
        body = body.replace(f"var(--{accent}-bg)", f"var(--{prefix}acb)").replace(f"var(--{accent})", f"var(--{prefix}ac)")
    return body


def convert(text):
    out = []
    for pre, body in blocks(text):
        if pre.startswith("@keyframes"):
            name = pre.split()[1]
            out.append(f"@keyframes {prefix}{name}{{{body}}}")
        elif pre.startswith(("@media", "@container", "@supports")):
            out.append(f"{pre}{{{convert(body)}}}")
        elif pre.startswith("@"):
            out.append(f"{pre}{{{body}}}")
        else:
            sels = [x for x in split_selectors(pre) if not MOCK_ONLY.match(x)]
            if sels:
                out.append(f"{','.join(scope(x) for x in sels)}{{{declarations(body)}}}")
    return "\n".join(out)


result = convert(css)
open(dst, "w").write(f"/* Generated by tools/port_mockup_css.py from {src}: the mockup's own styles, classes prefixed {prefix} and scoped under .{prefix}root. Do not edit; re-run the tool. */\n{result}\n")
print(f"{dst}: {len(result)} bytes")
